### ISSUE TITLE
Determine best visualization approach for sample hierarchies

### ISSUE THREAD

**Issue by keller-mark** [hms-dbmi/cistrome-explorer#13]
Often, hierarchical clustering will be performed on cohorts of samples (on the order of hundreds of samples), and we want to provide features for visualization of these hierarchies.

With hundreds of samples, it is likely that the leaves of dendrograms will be too dense for effective analysis tasks.

As a first step, I think it would be good to implement a regular dendrogram component ([slides 1-6](https://docs.google.com/presentation/d/1wDe_QpY5mI6nm7gYwFwzzxTjllnwT69vqIV4pBu3W2g/edit?usp=sharing)), 
- [x] regular dendrogram

and then explore the following alternatives:
- [ ] aggregated dendrograms (Liu, Zhan, Munzner 2019 IEEE TVCG)
- [ ] stacked trees (Bisson and Blanch 2012 AVI)
- [ ] cutting tree with slider ([clustergrammer example](https://maayanlab.github.io/kinase_substrate_similarity_network/))([slides 7-14](https://docs.google.com/presentation/d/1wDe_QpY5mI6nm7gYwFwzzxTjllnwT69vqIV4pBu3W2g/edit?usp=sharing))

**Comment by sehilyi** [comment]
Closing this issue since we already implemented a dendrogram that shows similarity scores
