### ISSUE TITLE
Aggregate rows "on the fly"

### ISSUE THREAD

**Issue by keller-mark** [hms-dbmi/cistrome-explorer#172]
We want to be able to aggregate along the y axis and display "summary rows" for groups by
- average
- variance, std. dev.
- sum
- ...

I think for now a good way to do this is to modify the higlass `selectRows` option to also take an array of arrays and add another option such as `selectRowsAggregationMode` that can take the values `"sum"`, `"mean"`, etc.

Then the aggregation function would be computed on each sub-array.

**Comment by sehilyi** [comment]
This looks like a good idea.

**Comment by keller-mark** [comment]
Even though we may not need this anymore since after our meeting it looks like there may only need to be one type of aggregation performed, which could be cached in a separate track data file, I am very close to having this feature finished so I think I will just try to polish up what I have so far in case we do end up needing it. Also once that is done we can try to push the limits and break it just so we have a sense of what is possible on the client-side in terms of aggregation.

**Comment by keller-mark** [comment]
Currently working on this higlass branch https://github.com/higlass/higlass/tree/keller-mark/select-rows-agg

**Comment by keller-mark** [comment]
Moving this one back to "To do" and un-assigning myself since now we will need to wait for the next higlass release to take advantage of the feature in the wrapper component
