### ISSUE TITLE
Clone view button should put the new view below rather than to the right

### ISSUE THREAD

**Issue by keller-mark** [hms-dbmi/cistrome-explorer#182]
<img width="288" alt="Screen Shot 2020-03-10 at 12 34 42 PM" src="https://user-images.githubusercontent.com/7525285/76336026-c5860800-62cb-11ea-97cb-b238680c8885.png">
 (this button)

This may already be a higlass option but if not we should implement it.

**Comment by sehilyi** [comment]
The main purpose of this issue is to prevent the overlap between wrapper components when cloned, right?

**Comment by keller-mark** [comment]
Yes, I think so

**Comment by sehilyi** [comment]
Because of the genomic selection bar on the bottom, adding a new view below of the original view would not work either.

I think we need to update higlass core to allow adding user-defined margins between views?

**Comment by keller-mark** [comment]
I like the user-defined margin idea. Another way we could implement it is to somehow listen for the new-view event and manually modify the view config to update the "layout" properties of each view to set the margins (https://github.com/hms-dbmi/cistrome-higlass-wrapper/blob/master/src/viewconfigs/horizontal-multivec-1.json#L135) but I am not sure if there is an event for that right now
