### ISSUE TITLE
Better formatting API result table

### ISSUE THREAD

**Issue by sehilyi** [hms-dbmi/cistrome-explorer#214]
Some possible improvements in the data table for the readability and space efficiency.

- [ ] Use scientific notations (e.g., "OverlapRatio")
- [ ] Use more readable formats of titles by not using the 'raw' variable names
   - e.g., "OverlapPeakNumber" => "Overlap Peak Number"
- [ ] Use consistent capitalization (e.g., "factor" vs. "Overlap ...")
- [ ] Reorder columns based on the field types and importance of values (e.g., we can refer to Cistrome Website for the column order, http://cistrome.org/db/#/).
- [ ] Remove the columns that are less likely to be interested by users 
   - e.g., "DCid"

<img width="887" alt="Screen Shot 2020-03-21 at 3 58 36 PM" src="https://user-images.githubusercontent.com/9922882/77235537-e59bae00-6b8c-11ea-8182-30712b779d1a.png">

**Comment by sehilyi** [comment]
With the given number of columns in the tables of query results, I think it is best to show the resulting table as a popup view, just like a heatmap options view in HiGlass:

![Screen Shot 2020-05-27 at 12 09 12 PM](https://user-images.githubusercontent.com/9922882/83045584-c3526080-a013-11ea-81e2-0daf63febf7d.png)

We originally thought of placing tables near visualizations in case users want to see information from the both views simultaneously, but it looks there is no known use cases that force us to place them together.

I will reshape the table and try adding new queries. If you have any other opinions, please let me know.

**Comment by keller-mark** [comment]
This sounds good. We could also try a "drawer" layout too.
Came across this through the higlass slack which uses the drawer concept:
https://index.altius.org

<img width="1552" alt="Screen Shot 2020-05-27 at 3 24 21 PM" src="https://user-images.githubusercontent.com/7525285/83063493-3c5eb180-a02e-11ea-8b39-d1ac28f51521.png">
<img width="1552" alt="Screen Shot 2020-05-27 at 3 24 25 PM" src="https://user-images.githubusercontent.com/7525285/83063505-42549280-a02e-11ea-91b7-6a1f6c89bb49.png">

**Comment by sehilyi** [comment]
Thanks for the suggestion @keller-mark. I've initially used the "modal" view (#257) since the table are currently too wide to use the "drawer" layout. But, the example above is really good looking and we can use the drawer layout in the future by considering to remove any less-useful information from our table and make them only visible on users' demand.
