### ISSUE TITLE
Generalize components by separating cistrome-specific functionality from multivec track metadata visualizations

### ISSUE THREAD

**Issue by sehilyi** [hms-dbmi/cistrome-explorer#237]
> Think more generalizing data input for our visualizations. 
> We may want to allow querying for any database and APIs.
> We can show a table as long as it has a common output format Array of JSON objects, one object for each row.

**Comment by keller-mark** [comment]
I propose that we move CistromeToolkit to a sibling of CistromeHGW

```
<CistromeHGW />
<CistromeToolkit />
```

and then rename CistromeHGW to something that is not cistrome-specific

```
<HiGlassWithMetadata />
<CistromeToolkit />
```

and wrap it all in a new CistromeExplorer component that manages things between the two

```
<CistromeExplorer>
    <HiGlassWithMetadata />
    <CistromeToolkit />
</CistromeExplorer>
```

then we could publish `HiGlassWithMetadata` to NPM eventually for others that want to view metadata with their multivec tracks and get all the cool sorting/filtering/highlighting functionality too.

**Comment by sehilyi** [comment]
I think this is good idea. I will reflect this comment when updating UIs for toolkit tables.

**Comment by keller-mark** [comment]
I am going to close this, I think this is done now with HiGlassMeta and CistromeToolkit components
